#ifndef CHAOTICMAPS_GLOBAL_H
#define CHAOTICMAPS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CHAOTICMAPS_LIBRARY)
#  define CHAOTICMAPSSHARED_EXPORT Q_DECL_EXPORT
#else
#  define CHAOTICMAPSSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CHAOTICMAPS_GLOBAL_H
